name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: anaj00
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, introduction, base.activity+community, base.repositories, achievements, followup, languages
          config_timezone: Asia/Manila
          commits_authoring: ${{ secrets.COMMIT_AUTHOR_LIST }}
          repositories_affiliations: owner, organization_member, collaborator
          repositories_skipped: Dwigoric/Dwigoric
          plugin_introduction: yes
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_followup_indepth: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          plugin_sponsors: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 30
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 1000
          plugin_languages_details: percentage, lines
          plugin_languages_sections: recently-used, most-used
